### ISSUE TITLE
Pesquisa em tag não possui navegabilidade

### ISSUE THREAD

**Issue by alaxalves** [crabsolutions/2016.2-Owla#100]
![captura de tela de 2016-11-23 17 51 29](https://cloud.githubusercontent.com/assets/19597045/20576578/9ee3c4f6-b1a5-11e6-9b23-0b0d06d93079.png)

**Comment by vitorbaraujo** [comment]
Acho legal mostrar "Você pesquisou por tal coisa", "20 resultados". E ter um botão de voltar também.

**Comment by matias310396** [comment]
Fazendo
