### ISSUE TITLE
Modal de criação da pergunta não desaparece depois de criar a pergunta

### ISSUE THREAD

**Issue by vitorbaraujo** [crabsolutions/2016.2-Owla#17]
Além disso, o texto da pergunta anterior ainda continua na caixa de texto

**Comment by luanguimaraesla** [comment]
Arrumado, falta só após o envio da pergunta limpar o campo de escrita para quando abrir a modal de novo não aparecer o texto anterior.

**Comment by luanguimaraesla** [comment]
Fechou: 05937a27, a limpeza de campo ainda não foi arrumada e está mapeada na issue #37
