### ISSUE TITLE
Slides não são deletados de /public/slides após a exclusão do tópico.

### ISSUE THREAD

**Issue by luanguimaraesla** [crabsolutions/2016.2-Owla#26]
Utilizei para segmentar o slide uma funcionalidade do RMagick que transforma cada página de um PDF em um arquivo JPG. Criei então para cada um dos tópicos um diretório nomeado com o ID do próprio que contém os segmentos do slide no seguinte formato: /public/slides/<id-do-topico/slide-<id-do-slide>.jpg.

Após a solicitação para exclusão de tópico, não há nenhum método para limpar esses diretórios de tópicos excluídos. O mesmo vale para o comando ```rake db:drop```, que apenas exclui os tópicos no banco, os slides segmentados continuam.

**Comment by vitorbaraujo** [comment]
Feito neste [commit](https://github.com/crabsolutions/2016.2-Owla/commit/ced2a2f7221c5c62a1c3dfa0be97634a3b5ea1a6). Quando subir pra devel eu fecho a issue
