### ISSUE TITLE
O HTML das questões criadas não está sendo renderizado corretamente

### ISSUE THREAD

**Issue by luanguimaraesla** [crabsolutions/2016.2-Owla#27]
As tags das questões criadas em HTML continuam aparecendo nas questões.

![image](https://cloud.githubusercontent.com/assets/11253021/20036822/3ddcb0fe-a3fa-11e6-95dc-97baa2add799.png)

**Comment by luanguimaraesla** [comment]
Vou arrumar isso.

**Comment by vitorbaraujo** [comment]
Consegui arrumar isso aqui (é só botar um `.html_safe` no `question.content`)

**Comment by vitorbaraujo** [comment]
@luanguimaraesla caso vc não commite aí, eu subo a modificação junto com as notificações. Me avisa se vc for subir isso.

**Comment by vitorbaraujo** [comment]
Resolvido em [ca84124](https://github.com/crabsolutions/2016.2-Owla/commit/ca84124da14aa18452d662711aafd3a715234d59)
