### ISSUE TITLE
Dropdown não abre depois que um link com stub é clicado

### ISSUE THREAD

**Issue by vitorbaraujo** [crabsolutions/2016.2-Owla#33]
Ao clicar em um stub, o dropdown só abre depois que a página é atualizada

![](http://i.imgur.com/cs8v104.png)

**Comment by vitorbaraujo** [comment]
Estou trabalhando nessa issue.

**Comment by luanguimaraesla** [comment]
O.o ainda está acontecendo esse problema após o merge? Não consegui replicar o bug.

**Comment by vitorbaraujo** [comment]
O problema é no dropdown das notificações (na header). Ainda não tá na devel. Vou dar o rebase na branch de notificações e ver se o problema ainda persiste.

**Comment by vitorbaraujo** [comment]
Subi pra devel as notificações e o erro parou de ocorrer.
