### ISSUE TITLE
Botões para trafego em slide com mau funcionamento

### ISSUE THREAD

**Issue by luanguimaraesla** [crabsolutions/2016.2-Owla#38]
Os botões que redirecionam os slides para direita e esquerda não estão funcionando como deveriam pois ocupam a coluna inteira "invisivelmente", ao clicar em qualquer posição imediatamente acima ou abaixo do botão, os slides são alterados. Isso é péssimo pois na maioria das vezes esse bug ocorre sobre o botão de enviar respostas ou marcar como anônimo.

**Comment by vitorbaraujo** [comment]
Eu consegui colocar as setas de navegação em cima do slide, porém não funciona quando a janela do navegador é redimensionado. Já com as setas de navegação do jeito que estão a responsividade funciona normalmente. Então, acho melhor deixar as setas do jeito que estão (somente deixando elas mais intuitivas para o usuário.

**Comment by vitorbaraujo** [comment]
Btw, está sendo feito nessa [branch](https://github.com/crabsolutions/2016.2-Owla/tree/issue_38_slide_buttons)
