### ISSUE TITLE
Primeiro acesso quebrando

### ISSUE THREAD

**Issue by luanguimaraesla** [crabsolutions/2016.2-Owla#39]
Algumas vezes o primeiro acesso à pagina quebra ao tentar carregar os Javascripts ou as folhas de estilo e basta carregar novamente para que tudo funcione perfeitamente.

**Comment by vitorbaraujo** [comment]
Será que pode ser isso? [http://stackoverflow.com/questions/23436210/javascript-doesnt-get-executed-the-first-time-when-i-access-a-page-from-a-link](http://stackoverflow.com/questions/23436210/javascript-doesnt-get-executed-the-first-time-when-i-access-a-page-from-a-link)

**Comment by luanguimaraesla** [comment]
Acho que não. Coloquei todos os Javascripts dentro de um ```$(document).ready()``` e parece que deu certo, não consegui mais replicar o bug depois disso.

**Comment by luanguimaraesla** [comment]
Merge #60

**Comment by vitorbaraujo** [comment]
Aparentemente está tudo ok
