### ISSUE TITLE
Forma como as tags são gerenciadas e criadas não apresenta usabilidade.

### ISSUE THREAD

**Issue by luanguimaraesla** [crabsolutions/2016.2-Owla#41]
As tags precisam ser editadas e criadas na própria janela onde as questões e respostas são colocadas, é importante também que o usuário possa selecionar quais cores deseja adicionar para cada uma das tags que criar.

**Comment by MartinsLucas** [comment]
Vou trabalhar nessa aqui.

**Comment by MartinsLucas** [comment]
Issue fechada no seguinte commit:
https://github.com/crabsolutions/2016.2-Owla/commit/3ba488ba24a02611a65e14b5ea52c52a155e42fa
