### ISSUE TITLE
Método .order não existe para arrays

### ISSUE THREAD

**Issue by luanguimaraesla** [crabsolutions/2016.2-Owla#42]
Temos que pensar outra maneira de fazer o ordenamento da lista de questões quando se trata da ordenação na página de slides, removi temporariamente e resolvi a issue.

![image](https://cloud.githubusercontent.com/assets/11253021/20157796/26e36246-a6be-11e6-93f7-89a367372c2f.png)

TODO: pensar em outra maneira de ordenar as questões do slide

**Comment by matheussbernardo** [comment]
Mandei pull request para resolver essa issue

**Comment by vitorbaraujo** [comment]
Resolvido neste [commit](https://github.com/crabsolutions/2016.2-Owla/commit/956433c02cf9a71a898a0fe7023bee48b2141a15)
