### ISSUE TITLE
Curtir não está em tempo real

### ISSUE THREAD

**Issue by luanguimaraesla** [crabsolutions/2016.2-Owla#45]
A opção curtir deve ser rigorosamente disponibilizada em tempo real

**Comment by vitorbaraujo** [comment]
Vou trabalhar nisso.

**Comment by vitorbaraujo** [comment]
Resolvido em [40b659](https://github.com/crabsolutions/2016.2-Owla/commit/40b65983df20dafc296b26d32bfaadda7cd52a42)
