### ISSUE TITLE
Melhorar navegabilidade na aplicação por meio de opção de voltar a páginas anteriores

### ISSUE THREAD

**Issue by vitorbaraujo** [crabsolutions/2016.2-Owla#49]

**Comment by Joranhezon** [comment]
Faltam os testes de aceitação para tal funcionalidade.

**Comment by Joranhezon** [comment]
Fechado nesse [commit](https://github.com/crabsolutions/2016.2-Owla/commit/0bbff7963e8353ccc18e00de5cd1ceac37b9f8d5)
