### ISSUE TITLE
Após editar perfil o usuário é redirecionado à index de member

### ISSUE THREAD

**Issue by MatheusRich** [crabsolutions/2016.2-Owla#67]
Não testei se dá pra apagar os outros membros.
![issue](https://cloud.githubusercontent.com/assets/20938712/20370529/5e442f3a-ac46-11e6-87df-f6b9838fcdf9.png)

**Comment by MatheusRich** [comment]
Sim, dá pra excluir e editar

**Comment by matheussbernardo** [comment]
Matheus Richard está fazendo essa

**Comment by MatheusRich** [comment]
Fechado nesse commit: https://github.com/crabsolutions/2016.2-Owla/commit/270c38505d5194d22a62ab8417b428dfb486158f
