### ISSUE TITLE
Bug na área de pesquisa ao usar botão sanduíche

### ISSUE THREAD

**Issue by MatheusRich** [crabsolutions/2016.2-Owla#68]
![issue](https://cloud.githubusercontent.com/assets/20938712/20371026/240ff1ca-ac49-11e6-8783-f58ecc57aa8f.jpg)

**Comment by vitorbaraujo** [comment]
Resolvido neste [commit](https://github.com/crabsolutions/2016.2-Owla/commit/4a6c82d4cb40b1e95ad12a39f9add4efd8276caf)
