### ISSUE TITLE
O botão de banir não desaparece após o membro ser banido

### ISSUE THREAD

**Issue by MatheusRich** [crabsolutions/2016.2-Owla#69]
![issue](https://cloud.githubusercontent.com/assets/20938712/20409989/251dd848-ad02-11e6-8ab4-d1d36a0b8924.png)

**Comment by vitorbaraujo** [comment]
Sendo feito por @Joranhezon e @ThalissonMelo [aqui](https://github.com/crabsolutions/2016.2-Owla/pull/80)

**Comment by vitorbaraujo** [comment]
Feito neste [commit](https://github.com/crabsolutions/2016.2-Owla/commit/85adffa890b02c977bcbc9873c557db2d39c674a)
