### ISSUE TITLE
Não há opção de banir nas respostas

### ISSUE THREAD

**Issue by MatheusRich** [crabsolutions/2016.2-Owla#70]
![issue2](https://cloud.githubusercontent.com/assets/20938712/20410017/48bca518-ad02-11e6-8bf1-232da650fc45.png)

**Comment by ThalissonMelo** [comment]
Fechado nesse [commit](https://github.com/crabsolutions/2016.2-Owla/commit/c5a6e129811efcb38878369fc0027e6bb058f10f)
