### ISSUE TITLE
Um nome de sala muito grande fica por cima dos links de navegabilidade

### ISSUE THREAD

**Issue by ThalissonMelo** [crabsolutions/2016.2-Owla#72]
![captura de tela de 2016-11-19 13-02-45](https://cloud.githubusercontent.com/assets/20938232/20456210/8c28c99c-ae58-11e6-81bc-b439e2664a5d.png)

**Comment by Joranhezon** [comment]
Fechada nesse commit: https://github.com/crabsolutions/2016.2-Owla/commit/c6a0da7433eb1b790832c56279f8f2a1dd88c515
