### ISSUE TITLE
Alterar um slide em um tópico que já contém um slide não funciona

### ISSUE THREAD

**Issue by matheussbernardo** [crabsolutions/2016.2-Owla#77]
Para replicar adicione um slide quando criar e depois em manage na view de topicos tente inserir outro slide.

**Comment by vitorbaraujo** [comment]
Vou mexer nisso agora

**Comment by vitorbaraujo** [comment]
Feito nesta [branch](https://github.com/crabsolutions/2016.2-Owla/tree/issue_38_slide_buttons). Quando subir pra devel eu fecho a issue.
