### ISSUE TITLE
Adicionar link para perfil de usuário

### ISSUE THREAD

**Issue by MatheusRich** [crabsolutions/2016.2-Owla#81]
![issue](https://cloud.githubusercontent.com/assets/20938712/20457422/2b01c776-ae72-11e6-844d-762beb44afa0.png)

**Comment by vitorbaraujo** [comment]
Resolvido neste [commit](https://github.com/crabsolutions/2016.2-Owla/commit/b3e11c81a6eeefcb463382bf0d88a5961ab8b3a4)
