### ISSUE TITLE
Na tela inicial não aparecem as suas próprias salas

### ISSUE THREAD

**Issue by MatheusRich** [crabsolutions/2016.2-Owla#83]
![issue](https://cloud.githubusercontent.com/assets/20938712/20457578/7b7c12d0-ae75-11e6-8323-a20bfc2c2bdb.png)

**Comment by matheussbernardo** [comment]
Estou trabalhando nessa issue.

**Comment by vitorbaraujo** [comment]
Resolvido neste [commit](https://github.com/crabsolutions/2016.2-Owla/commit/ed61c4b6188d3f256813a35f01686ae911115358)
