### ISSUE TITLE
Não mostrar notificações do próprio usuário respondendo suas perguntas

### ISSUE THREAD

**Issue by MatheusRich** [crabsolutions/2016.2-Owla#89]
![issue](https://cloud.githubusercontent.com/assets/20938712/20502985/b491644a-b027-11e6-9487-b06aac6f0b96.png)

**Comment by matias310396** [comment]
Fazendo

**Comment by vitorbaraujo** [comment]
Feito nesse [commit](https://github.com/crabsolutions/2016.2-Owla/commit/7cda2787aa9e2eece5a68ecf71c2f10c276b869a)
