### ISSUE TITLE
Descolem essas coisas, por favor

### ISSUE THREAD

**Issue by MatheusRich** [crabsolutions/2016.2-Owla#90]
![image](https://cloud.githubusercontent.com/assets/20938712/20503790/67d180b4-b02b-11e6-8a6c-baa342f4652c.png)

**Comment by jessicacris** [comment]
Fazendo

**Comment by vitorbaraujo** [comment]
Feito neste [commit](https://github.com/crabsolutions/2016.2-Owla/commit/e26bfcf24c9585d233e35115c7a9de20bad3d617)
